### ISSUE TITLE
Autoclose for doors without sensors

### ISSUE THREAD

**Issue by vwout** [vwout/zkaccess-c3-py#3]
As reported vwout/hass-zkaccess_c3#3:
> As not everyone will have sensors on all doors, maybe a feature request for the future is just to have the option to individually configure each door for a trigger time (rather than a global settings), and the option to turn sensor reporting on/off per door, giving you just a dumb unlock button for those without reporting.

The C3 panels have an unlock time specified for both doors and auxiliaries. For auxiliaries the library automatically reports closing, since there is no automatic feedback by the panel, but for doors this is not implemented, because doors report their own status. However only if there is a sensor present.
Ideally the library should autodetect whether a sensor is configured on only autoclose in that case.

**Comment by benofishal** [comment]
I don't think there is a way to get from the panel whether or not a sensor is installed as even in ZKAccess you have to manually configure it None/NO/NC

![image](https://github.com/vwout/zkaccess-c3-py/assets/25915750/d072fd8d-addb-4d88-9f6c-1a38cab4412f)

**Comment by vwout** [comment]
The autoclose is now default behavior in the library in case no sensor is configured. The sensor configuration needs to be applied using the ZKAccess tooling. The behavior is used in release [0.0.8](https://github.com/vwout/hass-zkaccess_c3/releases/tag/0.0.8) of the [Home Assistant integration](https://github.com/vwout/hass-zkaccess_c3).
