### ISSUE TITLE
Connection Reset error

### ISSUE THREAD

**Issue by hazem537** [vwout/zkaccess-c3-py#4]
get real time log for controller and put it in isolate process but give me error 
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\hazem\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\hazem\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hazem\Desktop\projects side\controoler\shift\processing.py", line 41, in get_real_time_log
    log = self.panel.get_rt_log()[0]
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazem\Desktop\projects side\controoler\env\Lib\site-packages\c3\core.py", line 544, in get_rt_log
    message, message_length = self._send_receive(self._rtlog_command)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazem\Desktop\projects side\controoler\env\Lib\site-packages\c3\core.py", line 207, in _send_receive
    receive_data, bytes_received, _ = self._receive()
                                      ^^^^^^^^^^^^^^^
  File "C:\Users\hazem\Desktop\projects side\controoler\env\Lib\site-packages\c3\core.py", line 165, in _receive
    header = self._sock.recv(5)
             ^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by hazem537** [comment]
i install latest version and eroor message changed
Traceback (most recent call last):
  File "C:\Users\hazem\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\hazem\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hazem\Desktop\projects side\controoler\shift\processing.py", line 42, in get_real_time_log
    log = self.panel.get_rt_log()[0]
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazem\Desktop\projects side\controoler\env\Lib\site-packages\c3\core.py", line 542, in get_rt_log
    message, message_length = self._send_receive(self._rtlog_command)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hazem\Desktop\projects side\controoler\env\Lib\site-packages\c3\core.py", line 205, in _send_receive
    receive_data, bytes_received, _ = self._receive()
                                      ^^^^^^^^^^^^^^^
  File "C:\Users\hazem\Desktop\projects side\controoler\env\Lib\site-packages\c3\core.py", line 193, in _receive
    raise ConnectionError(f"Invalid response header received; expected 5 bytes, received {header}")
ConnectionError: Invalid response header received; expected 5 bytes, received b''
all i need to get realtime log in infinte loop

**Comment by vwout** [comment]
Communication issues is something that appears to be standard with the panels. The result is an invalid connection. If you are in a continuous polling loop, you will want to gracefully disconnect and reconnect again.

For an example of a polling loop with handling of these exceptions, see my HomeAssistant integration for ZKAccess panels: https://github.com/vwout/hass-zkaccess_c3/blob/b19ae0fa8b19537d1208b4c3b568ecfdc25b450e/custom_components/zkaccess_c3/coordinator.py#L136

**Comment by hazem537** [comment]
i want to make code listen to socket 24 hour 7 day in week but as reason i dont kone it get aout and can not connect again to controller i am using muli processing and make process for every controller i have and that code i use  
def get_real_time_log (gate_id,panel):
        import django 
        django.setup()
        from gates.models import Gate
        from shift.models import ShiftDetail
        from card.models import ParkingCard,ParkingSession
      
        connect = panel.connect()
            
        if connect:
            gate = Gate.objects.get(pk=gate_id) 
            print(f"start listen on gate {gate.pk} ")
            while True:
                # get gate that working on
                    gate = Gate.objects.get(pk=gate_id) 
                # check connection
                
                    if (panel._connected ==False):
                        panel.connect()
                        
                    # wawant to open in  gate
                    if gate.open_in == True:
                        print(f"want to open in door for gate{gate.name}")
                        open_in_door(panel)
                        gate.open_in=False
                        gate.save()
                # want to open out  gate 
                    if gate.open_out ==True:
                        print(f"want to open out door for gate  {gate.name}")
                        open_out_door(panel)
                        gate.open_out=False
                        gate.save()
                        
                    try:
                        # check if any new some thing happen like some one in 
                        logs= panel.get_rt_log()
                        for log in logs :
                        # print(f" event type is {log.event_type}")
                            if log.event_type != 255    :
                                if log.card_no != 0 :
                                    # cleasr error of card number is zero may happen 
                                    print(f"{log.in_out_state}" )
                                
                                    # and log.in_out_state == 0
                                    print(f" in out state is {log.in_out_state}")
                                    print(log.card_no)
                                    try:
                                        card ,creatd=ParkingCard.objects.get_or_create(num = log.card_no)
                                        card.save()
                                        
                                        # ceck category master
                                        # have master category open fgor him not saving it 
                                        from  card.models import  Category
                                        cat,_  =  Category.objects.get_or_create(name="master")
                                        cat.save()
                                        if (card.category.pk == cat.pk ):
                                            open_in_door(panel)
                                            continue
                                            # if it normal cart it open gate and make new session for him 
                                        new_session= ParkingSession.objects .create(card=card,gate_in=gate)                          
                                        # get shift in to attach for hime if we can
                                        try:
                                            from shift.utilities import active_shift_ip
                                            shift =active_shift_ip(gate.pc_ip)
                                            shift =ShiftDetail.objects.get(pk=shift.id) 
                                        except Exception as e:
                                            print(e)
                                        new_session.shift_in=shift
                                        new_session.save()    
                                        # we should capture image here
                                        
                                        # then open door 
                                        open_in_door(panel)
                                        
                                    except Exception as e:
                                        print(e)  
                    except OSError as os_err: 
                        # any disconnection error close it and start it again
                        panel.disconnect()
                        # gate.panel=None
                        print(f"os err  {os_err}")  
                                
                    # except Exception as ex:
                    #       print(f"Exception is  {ex}")          

        else:
            # from gates.models import Error
            # Error.objects.create(source=f" gate {gate_id}",message="cant start connection").save()
            # print("Cant start connection ")          
            panel.disconnect()     



=========================
    def handle(self, *args, **options):
        import django
        django.setup()
        from sys import argv
        if 'makemigrations' in argv or 'migrate' in argv:
            return
        processes =[]
        from gates.models import Gate
        gates =Gate.objects.all()
        for gate in gates:
            panel = C3(gate.ip)
            process= multiprocessing.Process(target=get_real_time_log ,args=(gate.pk,panel) )
            process.start ()
            processes .append((process,gate.pk,panel))
            
            
            
        while True: 
            for idx, (process, gate_pk, panel) in enumerate(processes):
                if not process.is_alive():
                    print(f"Process for gate {gate_pk} crashed. Restarting...")
                    new_process = multiprocessing.Process(target=get_real_time_log, args=(gate_pk, panel))
                    new_process.start()
                    processes[idx] = (new_process, gate_pk, panel)    
and that code make process if thjer is approach to solve this problem
